Fix xdot parsing
Spurious `\` chars cause xdot to fail parsing dot files generated by radeco.

To reproduce:
	mm7@pc7:~/prj/radare2/radeco$ ./target/debug/radeco ../radeco-lib/ex-bins/simple2 -b -c "dot sym.main" > a.dot
	Module version mismatch /home/mm7/.local/share/radare2/plugins/radeco_pde.so (3.2.0-git) vs (3.3.0-git)
	[*] Fixing Callee Information
	mm7@pc7:~/prj/radare2/radeco$ xdot a.dot
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1605, in set_dotcode
	    self.set_xdotcode(xdotcode)
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1620, in set_xdotcode
	    self.graph = parser.parse()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1289, in parse
	    DotParser.parse(self)
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1086, in parse
	    self.parse_graph()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1095, in parse_graph
	    self.parse_stmt()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1125, in parse_stmt
	    self.parse_subgraph()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1108, in parse_subgraph
	    self.parse_stmt()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1140, in parse_stmt
	    attrs = self.parse_attrs()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1150, in parse_attrs
	    name, value = self.parse_attr()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1162, in parse_attr
	    value = self.parse_id()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1186, in parse_id
	    self.consume()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 967, in consume
	    self.lookahead = next(self.lexer)
	  File "/usr/lib/python3/dist-packages/xdot.py", line 917, in __next__
	    raise ParseError(msg, self.filename, line, col)
	xdot.ParseError: 666:63:unexpected char b'\\'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/bin/xdot", line 4, in <module>
	    xdot.main()
	  File "/usr/lib/python3/dist-packages/xdot.py", line 2163, in main
	    win.open_file(args[0])
	  File "/usr/lib/python3/dist-packages/xdot.py", line 2074, in open_file
	    self.set_dotcode(fp.read(), filename)
	  File "/usr/lib/python3/dist-packages/xdot.py", line 2056, in set_dotcode
	    if self.dotwidget.set_dotcode(dotcode, filename):
	  File "/usr/lib/python3/dist-packages/xdot.py", line 1607, in set_dotcode
	    self.error_dialog(str(ex))
	AttributeError: 'DotWidget' object has no attribute 'error_dialog'